### PR TITLE
Add symlink to LICENSE file so it is included in the calibright library crate

### PR DESCRIPTION
**Pull request by blinxen**
The `calibright` library crate does not ship a license file on crates.io. This PR fixes this.

You also might want to fix [this](https://github.com/bim9262/calibright/blob/main/LICENSE#L655) license file. It is missing `project`, `year` and the `fullname` attribute of the license file.

### CODE REVIEW

**Comment by bim9262** [comment]
@blinxen, it's my understanding that the license file should not be included, unless it's a non-standard license.

https://crates.io/crates/calibright shows that this is under [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html)
I will update the `project`, `year` and the `fullname` though. 

Thanks for flagging this and please let me know if I misunderstood something about including the license file as part of the crate.

**Comment by HusseinKabbout** [comment]
> I will update the project, year and the fullname though.

This was a misunderstanding from my side. These fields should stay not filled in because they are in the appendix. You can keep them as they are.

> it's my understanding that the license file should not be included, unless it's a non-standard license.

Not sure where you read that, do you have a source? It is standard to always include the license file.

**Comment by blinxen** [comment]
>I will update the project, year and the fullname though.

This was a misunderstanding from my side. These fields should stay not filled in because they are in the appendix. You can keep them as they are.

> it's my understanding that the license file should not be included, unless it's a non-standard license.

Not sure where you read that, do you have a source? It is standard to always include the license file.

**Comment by bim9262** [comment]
Based on https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields and the associated warning cargo gives when both `license` and `license-file` are set.

**Comment by blinxen** [comment]
You don't have to set `license-file` here. What is meant by the documentation is that when using a non-standard license, for example a license with no corresponding SPDX identifier, then you have to use `license-file`. My PR does not do that, my PR simply links the license file, corresponding to your SPDX identifier, so it is included with the code.

**Comment by blinxen** [comment]
[serde-rs](https://github.com/serde-rs/serde/tree/master/serde) does this too. (And a lot of other crates too)

**Comment by bim9262** [comment]
@blinxen after doing some more reading (https://github.com/rust-lang/cargo/issues/8537) and several other related tickets, it does seem like the symlink is the best option (even though it feels hacky). I guess the same should be done in the bin directory too (calibright_cli).

**Comment by bim9262** [comment]
Merged https://github.com/bim9262/calibright/commit/025bd6b3b58042b2cb23a99f94e1b0a9d9c68c8b

**Pull request closed without merging**
