### PR TITLE
update zbus to v4

### PR DESCRIPTION
**Pull request by MaxVerevkin**
I also had to `cargo update` because I got errors on nightly. The actual change is two lines :)

### CODE REVIEW

**Comment by bim9262** [comment]
Seems like just zbus and Tokio could be updated instead of updating everything. How to pick between only updating the minimum required dependencies or updating all the dependencies?

**Comment by MaxVerevkin** [comment]
The error is 

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/maxv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

If I run just `cargo update -p proc-macro2` I get errors like

```
Checking zbus v4.0.1
error[E0277]: the trait bound `ReadBuf<'_>: bytes::buf::buf_mut::BufMut` is not satisfied
   --> /home/maxv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.0.1/src/connection/socket/tcp.rs:110:23
    |
110 |         self.read_buf(&mut read_buf).await.map(|_| {
    |              -------- ^^^^^^^^^^^^^ the trait `bytes::buf::buf_mut::BufMut` is not implemented for `ReadBuf<'_>`
    |              |
    |              required by a bound introduced by this call
```

which is now `zbus`'s fault for not specifying min versions correctly. Updating `tokio` fixes it. But then after all this, running `cargo update` removes some duplicated dependencies...

**Comment by bim9262** [comment]
Sorry to have gotten distracted on this. Since the zbus update is a breaking change should this be a minor version update for calibright?

**Comment by MaxVerevkin** [comment]
Is it? It is not exposed in the API anywhere, right?

**Comment by bim9262** [comment]
I wasn't sure if this error counts or not (ex compiling i3status-rs with the version updated version of calibright)

```
error: failed to select a version for `zvariant_utils`.
    ... required by package `zbus_macros v4.0.0`
    ... which satisfies dependency `zbus_macros = "=4.0.0"` of package `zbus v4.0.0`
    ... which satisfies dependency `zbus = "^4.0"` of package `calibright v0.1.5 (/home/bmalyn/Documents/Code/rust/calibright/lib)`
    ... which satisfies dependency `calibright = "^0.1"` (locked to 0.1.5) of package `i3status-rs v0.33.0 (/home/bmalyn/Documents/Code/rust/i3status-rust)`
    ... which satisfies path dependency `i3status-rs` (locked to 0.33.0) of package `xtask v0.1.0 (/home/bmalyn/Documents/Code/rust/i3status-rust/xtask)`
versions that meet the requirements `=1.1.0` are: 1.1.0
```

Normally you can have multiple version of a dependency, but it doesn't seem like that's the case here.

**Comment by bim9262** [comment]
Oh nevermind that's just from not updating the version of calibright to 0.1.6.

**Comment by MaxVerevkin** [comment]
Eh, they messed up somewhere... A non-compatible version change is a safer option, I suppose.

Edit: I remember a very similar error when updating i3status-rs without calibright, so there is definitely something wrong.

**Pull request merged**
